# vim: set ft=yaml:
---
- inventory:
    all:
      - fritz.box
      - esel.fritz.box
      - heimbot.fritz.box
    fritz_box:
      - fritz.box
    esel:
      - esel.fritz.box
    raspi:
      - heimbot.fritz.box


- hosts: all
  properties:
    - name: Check SSH
      ssh: { port: 22, version: 2.0, software: "OpenSSH.*" }


- hosts: fritz_box
  properties:
    - name: DNS TCP
      connect_tcp:
        port: 53
    - name: DNS UDP
      dns_udp:
        port: 53
    - name: SIP TCP
      connect_tcp:
        port: 5060
    - name: Check for HTTP
      http:
        port: 80
        verb: GET
        uri: /
        response_code: 200
    - name: Check for HTTP on 8181
      http:
        port: 8181
        verb: GET
        uri: /
        response_code: 404
    - name: Check for HTTPS
      https:
        port: 443
        verb: GET
        uri: /
        response_code: 200


- hosts: esel
  properties:
    - name: NetBios TCP Port
      connect_tcp:
        port: 139
    - name: SNMP TCP Port
      connect_tcp:
        port: 161
    - name: Microsoft DS TCP Port
      connect_tcp:
        port: 445
    - name: Apple File Protocol TCP Port
      connect_tcp:
        port: 548
    - name: RSync TCP Port
      connect_tcp:
        port: 873
    - name: RSync TCP Port
      connect_tcp:
        port: 873
    - name: UPNP TCP Port
      connect_tcp:
        port: 5000
    - name: Check HTTP Redirect to HTTPS
      http:
        port: 5000
        verb: GET
        uri: /
        response_code: 302
    - name: Check for HTTPS
      https:
        port: 5001
        verb: GET
        uri: /
        response_code: 200


- hosts: raspi
  properties:
    - name: Check HTTP Redirect to HTTPS
      http:
        port: 80
        verb: GET
        uri: /
        response_code: 301
    - name: Check for HTTPS
      https:
        port: 443
        verb: GET
        uri: /
        response_code: 200
    - name: Check for HTTPS (Fhem)
      https:
        port: 8083
        verb: GET
        uri: /
        response_code: 302
    - name: Check for HAProxy Admin UI
      http:
        port: 8404
        verb: GET
        uri: /monitor
        response_code: 401

